### ISSUE TITLE
Server-Konfiguration

### ISSUE THREAD

**Issue by MKattaa** [thm-mni-ii/SWTP_WS19-20_framework#1]
### Die Gruppe ist auf der Suche nach der richtigen Server Konfigurationspattform.

**Comment by MKattaa** [comment]
Als Beispiele für die Server-Konfiguration habe ich zwei mögliche Beispiele im Internet gefunden, die sind: 
1. Nakama server, **Quellen:**
   1. https://assetstore.unity.com/packages/tools/network/nakama-81338 
   1. https://github.com/MKattaa/nakama
   1. https://heroiclabs.com/docs/
1. Master Server Framework, **Quellen:**
   1. https://assetstore.unity.com/packages/tools/network/master-server-framework-71391
   1. https://github.com/alvyxaz/barebones-masterserver/wiki

**Comment by Azem7** [comment]
Anstatt von UNET sind die folgende Technologien verwendbar:
1. Mirror
https://assetstore.unity.com/packages/tools/network/mirror-129321

-Ermöglicht game lobby/Room
-Server/Client funktioniert (getestet in localhost) 
- [Server] / [Client] -Tags können für die Nur-Server- und Nur-Client-Teile verwendet werden
- [Command]s werden für die Client-> Server-Kommunikation verwendet
- [ClientRpc] / [TargetRpc] für Server-> Client-Kommunikation
- [SyncVar] s und SyncLists werden verwendet, um den Status automatisch zu synchronisieren.

2. Nakama
https://assetstore.unity.com/packages/tools/network/nakama-81338

Benutzerkonten mit optionaler sozialer Anmeldung über Facebook, Steam, Game Center usw.
- Datenspeicher zum Speichern von Spielen, Karten, Gegenständen und anderen Gameplay-Objekten.
- In-Game-Chat in Gruppen, 1-zu-1 und Welt-Chat mit beständiger Geschichte!
- Freundeslisten für Personen, die online sind, kombiniert mit Facebook und benutzerdefinierten Listen.
- Matchmake mit Leuten und Freunden, die online sind.
- Aktiver oder passiver Multiplayer in Echtzeit (und rundenbasiert).
- Social Graph zwischen Benutzergruppen für Gilden und Clans.

**Comment by Azem7** [comment]
Der server werden wir lokal konfigurieren, da wir keine geeignete Hosting-Service finden konnten.

https://www.a2hosting.com/database-hosting

https://www.hosteurope.de/WebHosting/gclid=EAIaIQobChMI0suGz6W85QIVBed3Ch26ug0WEAAYBCAAEgKvB_D_BwE

https://alfahosting.de/server-hosting/

**Comment by MKattaa** [comment]
![GlobalCanvas - Networkmanager](https://user-images.githubusercontent.com/53947632/74604363-9b229f80-50bd-11ea-8987-61dc64855b91.png)

**Comment by MKattaa** [comment]
![Informationsaustausch-Server](https://user-images.githubusercontent.com/53947632/74604369-a1188080-50bd-11ea-93ab-27193a533659.png)

**Comment by MKattaa** [comment]
![Informationsaustausch-Server](https://user-images.githubusercontent.com/53947632/74604393-d7560000-50bd-11ea-96d5-2be53e0aad6b.png)

**Comment by MKattaa** [comment]
![Mirror IP-Konfig](https://user-images.githubusercontent.com/53947632/74604395-dcb34a80-50bd-11ea-94bf-d15b3b335989.png)
