### ISSUE TITLE
Die Datenbank erweitern

### ISSUE THREAD

**Issue by MKattaa** [thm-mni-ii/SWTP_WS19-20_framework#33]
Die Datenbank muss so erweitert wird, dass man die Fragen von der andere Gruppe einfügen kann.

**Comment by Azem7** [comment]
Neue Data Definitionen addiert
Moudles Liste und Games Liste

Syntax:

{     "OOP": {
       "Dozent": "Uberall",
       "Creditpoints": "6"     },

    	"GDI": {
       "Dozent": "Herzberg",
       "Creditpoints": "6"     },

    	"RNAI": {
       "Dozent": "Muller",
       "Creditpoints": "6"     },

    	"MATH": {
       "Dozent": "Metz",
       "Creditpoints": "6"     },
     
	"NTG": {
       "Dozent": "Rinn",
       "Creditpoints": "6"     }
}

{
  "Dexit": {
       "Maxplayers": "5",
       "Minplayers": "3"     }
}
