### ISSUE TITLE
Anwendbare Technologien bzw. Programme

### ISSUE THREAD

**Issue by MKattaa** [thm-mni-ii/SWTP_WS19-20_framework#4]
Mirror

**Comment by damasjasmine** [comment]
Möglichkeiten für RealTime Chat with Unity zu verwenden:
https://unity.chat/
https://assetstore.unity.com/packages/tools/network/photon-chat-45334

**Comment by MKattaa** [comment]
**Doxygen** ist ein freies Software-Dokumentationswerkzeug unter der GNU General Public License, **_das wir verwenden können._**

**Comment by MKattaa** [comment]
Wir haben uns geeinigt Unity 2019.2.10f1 zu verwenden
